### ISSUE TITLE
Korrektur von Sprachwechsel und Spracheinstellung

### ISSUE THREAD

**Issue by windauer** [humboldtdigital/ProHD#22]

**Comment by windauer** [comment]
@arojascastro will provide more information

**Comment by tuurma** [comment]
Browser language settings take precedence over the selection made via the pb-lang component: this problem manifests in About and Team pages.

**Comment by windauer** [comment]
@tuurma sound exactly like the issue I just recently fixed: https://github.com/eeditiones/tei-publisher-app/pull/185

**Comment by arojascastro** [comment]
The problem lies in files about the project and team in /data:

- about.xml (German)
- about_en.xml (English)
- about_es.xml (Spanish)
- team.xml (German)
- team_en.xml (English)
- team_es,xml (Spanish)

We have tested the web application with users, whose language computer is English and Spanish, and they had troubles when accessing those pages: they were browsed by default in German and even when they switched the langauge manually to English or Spanish, the page did not load automatically to the selected languages. 

Our expected behaviour is that the pages are accessed according to the language system of each user and that, when they select manually another language, that the page is refreshed automatically.

Please let me know if you need further questions or doubts.

**Comment by tuurma** [comment]
Also switching the language with the pb-lang has no effect on the content, only the `pb-i18n` labels

**Comment by tuurma** [comment]
Should be now fixed.

I've put in a placeholder for criterios_en.xml and criterios.xml needs to be translated to German, for the moment all hold Spanish content.
