### ISSUE TITLE
Verbesserte Seitennavigation

### ISSUE THREAD

**Issue by windauer** [humboldtdigital/ProHD#23]
Verbesserte Seitennavigation (zwischen <pb>), z.B. mit einer Dropdown-Liste und der Angabe der Länge des Dokuments, analog zum Beispiel der Rabbinica (Select Folio), vgl.

**Comment by windauer** [comment]
http://localhost:8080/exist/apps/ProHD/criterios.xml

**Comment by tuurma** [comment]
- in the document view extend the toolbar with a dropdown listing all folios in the current document; selecting one should lead to this exact page
- perhaps add a thumbnail strip to the facsimile

**Comment by tuurma** [comment]
use `pb/@n` for the dropdown labels

**Comment by tuurma** [comment]
Search by page label

<img width="945" alt="image" src="https://github.com/humboldtdigital/ProHD/assets/449468/0fa2532c-709c-4116-b5b7-19d8c616bd7e">

or otherwise see all available pages looking for `*`

<img width="937" alt="image" src="https://github.com/humboldtdigital/ProHD/assets/449468/76420cc3-0c42-4694-a403-76f38aa79c69">
